import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ReactElement, ReactNode, useState } from "react";

const shortenedUrl = (url: string) => {
  if (url === "") {
    return <></>;
  }
  return (
    <div className="text-center">
      Here is your shortened url:{" "}
      <a className="font-bold block  underline text-blue-400" href={url}>
        {url}
      </a>
      {/* Click here to copy to clipboard */}
      <button
        className="block font-bold text-center w-full p-4"
        onClick={() => {
          navigator.clipboard.writeText(url);
        }}
      >
        {" "}
        Click here to copy to clipboard{" "}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const [url, setUrl] = useState("");
  const [long, setLong] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [Customize, setCustomize] = useState("hidden");
  const [slug, setSlug] = useState("");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    const nurl: string =
      long.startsWith("http") || long.startsWith("https")
        ? long
        : `https://${long}`;

    if (
      !/^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/.test(
        nurl
      )
    ) {
      alert("invalid url");
      setIsLoading(false);
      return;
    }
    if (!/^[A-Za-z1-9-]{1,15}$/.test(slug) && slug !== "") {
      alert("invalid slug");
      setIsLoading(false);
      return;
    }
    const res = await fetch("/api/add-url", {
      method: "POST",
      body: JSON.stringify({ url: nurl,
      slug: slug == "" ? null : slug }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await res.json();
    if (!res.ok) {
      throw new Error(data.message);
      alert(data.message);
    }
    console.log(data.link);
    setUrl(data.link);
    setLong("");
    setIsLoading(false);
  };
  //if loading put a gray box on top of the form
  const loading = isLoading ? (
    <div className="absolute top-0 left-0 w-full h-full bg-gray-200 opacity-50 z-10"></div>
  ) : (
    <></>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Link Shortener | cock.hu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{loading}</div>
        <h1 className="text-3xl font-bold text-center uppercase mb-16">
          cock.hu <br />{" "}
          <p className="text-xl p-2">The world&apos;s best link shortener </p>
        </h1>
        <div className="rounded-lg border-gray-600 min-w-[350px] max-w-[600px] w-5/6  border-2 p-8">
          <p className="text-center font-bold p-4">
            Enter the link you want to shorten!
          </p>

          <div className="transition ease-in-out">{shortenedUrl(url)}</div>

          <form method="POST" onSubmit={handleSubmit}>
            <label
              htmlFor="url"
              className="text-gray-400 block pl-2 uppercase pb-1"
            >
              Url <p className="m-0 p-0 inline text-[0.5rem]">(required)</p>
            </label>
            <input
              type={"text"}
              className="bg-gray-800 rounded-md outline-none p-4 w-full font-RobotoMono"
              placeholder="Url..."
              name="url"
              required
              onChange={(e) => {
                setLong(e.target.value);
              }}
              value={long}
            ></input>
            <button
              className="font-bold text-xs text-right w-full underline font-RobotoMono"
              type="button"
              onClick={() => {
                if (Customize === "hidden") {
                  setCustomize("");
                } else {
                  setCustomize("hidden");
                }
              }}
            >
              Customize
            </button>
            <div className={Customize}>
              <label
                htmlFor="slug"
                className="text-gray-400 block pl-2 uppercase pb-1"
              >
                Slug
              </label>

            <input
              type={"text"}
              className={
                "bg-gray-800 rounded-md outline-none p-4 w-full font-RobotoMono" +
                " " 
              }
              placeholder="Custom slug..."
              name="slug"
              onChange={(e) => {
                setSlug(e.target.value);
              }}
              value={slug}
            ></input>
            </div>
            <button
              type="submit"
              className="bg-gray-100 hover:bg-gray-300  transition-all	ease-in-out  rounded-md  text-black outline-none p-4 w-full font-RobotoMono mt-4"
            >
              Shorten!
            </button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
