import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";



const shortenedUrl = (url: string) => {
  if (url === "") {
    return <></>
  }
  return (
    <div className="text-center">
      Here is your shortened url:{" "}
      <a className="font-bold block  underline text-blue-400" href={url}>
        {url}
      </a>
      {/* Click here to copy to clipboard */}
      <button
        className="block font-bold text-center w-full p-4"
        onClick={() => {
          navigator.clipboard.writeText(url);
        }}
      >
        {" "}
        Click here to copy to clipboard{" "}
      </button>
    </div>
  );

}
  
  

const Home: NextPage = () => {
  const [url, setUrl ] = useState("")
  const [long , setLong] = useState("")

  const handleSubmit = async (
    e: React.FormEvent<HTMLFormElement>
  ) => {
    e.preventDefault();
    const res = await fetch("/api/add-url", {
      method: "POST",
      body: JSON.stringify({ url: e.currentTarget.url.value }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const data = await res.json();
    if (!res.ok) {
      throw new Error(data.message);
      alert(data.message);
    }
    console.log(data.link)
    setUrl(data.link);
    setLong("")
    
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Link Shortener | cock.hu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold text-center uppercase mb-16">
          cock.hu <br />{" "}
          <p className="text-xl p-2">The world&apos;s best link shortener </p>
        </h1>
        <div className="rounded-lg border-gray-600  border-2 p-8">
          <p className="text-center font-bold p-4">
            Enter the link you want to shorten!
          </p>

          <div className="transition ease-in-out">{shortenedUrl(url)}</div>

          <form method="POST" onSubmit={handleSubmit}>
            <label
              htmlFor="url"
              className="text-gray-400 block pl-2 uppercase pb-1"
            >
              Url
            </label>
            <input
              type={"text"}
              className="bg-gray-800 rounded-md outline-none p-4 w-full font-RobotoMono"
              placeholder="Url..."
              name="url"
              required
              onChange={(e) => {
                setLong(e.target.value);
              }}
              value={long}
              pattern="https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)"
            ></input>
            <button className="bg-gray-100 hover:bg-gray-300  transition-all	ease-in-out  rounded-md  text-black outline-none p-4 w-full font-RobotoMono mt-4">
              Shorten!
            </button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;
